<a href="https://colab.research.google.com/github/rpolea/CE888/blob/main/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [111]:
df= pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv',header=None)

In [112]:
df.head(10)
df.shape

(24983, 101)

In [113]:
df = df.replace(99, np.nan)

In [114]:
df = df.drop([0], axis = 1)

In [115]:
df.describe()

1             2    ...           99           100
count  16452.000000  18184.000000  ...  10910.000000  9943.000000
mean       0.904573      0.208460  ...     -0.031244     1.354711
std        5.171798      5.597327  ...      5.176806     5.300409
min       -9.950000     -9.950000  ...     -9.950000    -9.950000
25%       -2.670000     -4.420000  ...     -4.170000    -2.330000
50%        1.600000      0.830000  ...      0.290000     2.140000
75%        4.900000      4.820000  ...      3.980000     5.730000
max        9.370000      9.370000  ...      9.370000     9.370000

[8 rows x 100 columns]

In [116]:
df.shape

(24983, 100)

In [117]:
df.head(2)

1     2     3     4     5     6    ...   95    96    97    98    99    100
0 -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1  4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07

[2 rows x 100 columns]

In [119]:
#To find out the average rating of the lowest/highest
joke_mean_sorted = sorted(df.mean())
joke_mean_max = max(joke_mean_sorted)
joke_mean_min = min(joke_mean_sorted)

print('Max ', joke_mean_max, 'Min ', joke_mean_min)
#print('Full list sorted: ')
#joke_mean_sorted

Max  3.6650848950824937 Min  -3.8338796373689923


In [125]:
#Finds specific value of user and joke
df.iloc[13051,17]

-8.5

In [10]:
arr = df.values
arr

array([[100.  ,   4.08,  -0.29, ...,   0.34,  -4.32,   1.07],
       [ 49.  ,    nan,    nan, ...,    nan,    nan,    nan],
       [ 48.  ,    nan,   8.35, ...,    nan,    nan,    nan],
       ...,
       [ 39.  ,    nan,    nan, ...,    nan,    nan,    nan],
       [ 37.  ,    nan,    nan, ...,    nan,    nan,    nan],
       [ 72.  ,   2.43,   2.67, ...,    nan,    nan,    nan]])

In [39]:
def replace(orig, percentage):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """

  new_data = orig.copy()
  rated = np.where(np.isnan(arr))
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [40]:
user_ratings,idx = replace(arr, 0.1)

In [41]:
user_ratings

array([[100.  ,   4.08,  -0.29, ...,   0.34,  -4.32,   1.07],
       [ 49.  ,    nan,    nan, ...,    nan,    nan,    nan],
       [ 48.  ,    nan,   8.35, ...,    nan,    nan,    nan],
       ...,
       [ 39.  ,    nan,    nan, ...,    nan,    nan,    nan],
       [ 37.  ,    nan,    nan, ...,    nan,    nan,    nan],
       [ 72.  ,   2.43,   2.67, ...,    nan,    nan,    nan]])

In [14]:
n_latent_factors = 4

latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [15]:
latent_user_preferences

array([[0.10845279, 0.76831477, 0.28393378, 0.18136221],
       [0.03733479, 0.70630703, 0.28258182, 0.3384407 ],
       [0.40639239, 0.93066475, 0.90244112, 0.81213906],
       ...,
       [0.06086973, 0.34863216, 0.2241462 , 0.08032465],
       [0.06853117, 0.32606904, 0.21267217, 0.42520294],
       [0.4926085 , 0.14443879, 0.55123938, 0.52966231]])

In [16]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if (rating != 99 and not np.isnan(rating)):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
        mse_history.append(mse)
    return mse_history

In [18]:
sgd(150)

Iteration 0/150:	MSE=48.447623
Iteration 1/150:	MSE=30.765300
Iteration 2/150:	MSE=26.537907


KeyboardInterrupt: ignored

In [29]:
#prediction for validation set
error_list = []
for i,j in zip(idx[0],idx[1]):
  error_list.append(predict_rating(i,j) - arr[i,j])

final_mse = (np.array(error_list)**2).mean()
print(final_mse)

24.191781598902125


In [30]:
#prediction for nans
np.where(np.isnan(arr))

for i,j in zip(np.where(np.isnan(arr))[0], np.where(np.isnan(arr))[1]):
  arr[i,j] = predict_rating(i,j)

In [31]:
np.where(np.isnan(arr))

(array([], dtype=int64), array([], dtype=int64))

In [20]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[ 8.88359710e+01,  1.00811675e+00,  3.20929824e-01, ...,
         8.34621966e-01, -1.35305732e-01,  1.21169853e+00],
       [ 5.24709099e+01,  6.10803008e-01,  2.43422575e-01, ...,
         5.15250345e-01, -1.34180046e-01,  6.52726817e-01],
       [ 5.86698423e+01,  7.36569201e-01,  2.47614889e-01, ...,
         5.96535418e-01, -1.72896863e-01,  7.84935671e-01],
       ...,
       [ 3.58559814e+01,  4.16165065e-01,  1.26656807e-01, ...,
         3.31029628e-01, -8.62958443e-02,  4.89385755e-01],
       [ 3.69576887e+01,  4.57580360e-01,  1.65579343e-01, ...,
         4.04016059e-01, -3.23554675e-02,  5.01296977e-01],
       [ 7.17827581e+01,  8.77368269e-01,  1.56362211e-01, ...,
         7.27557775e-01,  5.68472376e-02,  1.17715058e+00]])

In [22]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [23]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

0    ...                          100
0      (100.0, 88.83597104956029)  ...   (1.07, 1.2116985307186747)
1      (49.0, 52.470909916283176)  ...    (nan, 0.6527268170089501)
2      (48.0, 58.669842306869285)  ...    (nan, 0.7849356710194263)
3       (91.0, 94.10746065409717)  ...    (1.6, 1.5370684497831835)
4      (100.0, 83.84097977995802)  ...  (-3.45, 1.2178507777839864)
...                           ...  ...                          ...
24977  (100.0, 97.33202091676304)  ...   (7.43, 1.3130370884191969)
24978   (91.0, 83.70213773415188)  ...   (8.45, 1.3256734102635657)
24979   (39.0, 35.85598139595351)  ...    (nan, 0.4893857551975003)
24980   (37.0, 36.95768872887159)  ...    (nan, 0.5012969772338336)
24981   (72.0, 71.78275812671887)  ...    (nan, 1.1771505789545047)

[24982 rows x 101 columns]

In [126]:
#movies dataset

#Matrix for movies and their factors
movie_items_data = pd.read_excel('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/movies_latent_factors.xlsx', sheet_name='Items')
#Matrix for users and their factors
movie_users_data = pd.read_excel('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/movies_latent_factors.xlsx', sheet_name='Users')

In [127]:
movie_users_data

User   Factor1   Factor2   Factor3  ...  Factor12  Factor13  Factor14  Factor15
0   4768 -0.204024  0.161079 -0.090447  ...  0.355404  0.007108 -0.118663 -0.039125
1    156 -0.189652 -0.178979 -0.091490  ... -0.048606  0.045916  0.113671  0.179873
2   5323 -0.115308 -0.090886 -0.053129  ... -0.019460  0.108372  0.054471 -0.109552
3    174 -0.227462 -0.272532 -0.017231  ... -0.082396  0.036767 -0.165438  0.050692
4   4529 -0.014616 -0.102218 -0.107935  ... -0.132836 -0.039897  0.129063  0.102669
5    783 -0.020301 -0.031919 -0.036955  ...  0.059725 -0.021647  0.039873 -0.061857
6   3878 -0.091462  0.215879 -0.180453  ...  0.214467  0.189250  0.065990  0.102776
7    768  0.000819 -0.009229 -0.019228  ... -0.010051 -0.002108  0.043223 -0.006670
8   4469 -0.030528 -0.011537 -0.042822  ...  0.010926  0.024400  0.005318 -0.007983
9   1882 -0.083093 -0.029160  0.013748  ... -0.113364 -0.021325  0.181508  0.022357
10  4997 -0.185443 -0.276496 -0.781275  ...  0.103116 -0.100563  0.100164  0.043196
11  2067 -0.083242  0.181171 -0.344267  ... -0.127038  0.176661 -0.055812 -0.000042
12  3806 -0.042344 -0.040755 -0.055720  ... -0.040915 -0.130308 -0.021816  0.034549
13  2848 -0.113283 -0.098942 -0.040393  ...  0.036894  0.067105 -0.016780 -0.029503
14  4433 -0.298760 -0.290228 -0.160120  ...  0.071371 -0.415598 -0.022139 -0.183021
15  3519 -0.068454  0.020090  0.039336  ...  0.005171  0.005546  0.020780 -0.023623
16  5338 -0.061259  0.014661  0.011412  ...  0.031774 -0.062413  0.107708  0.065081
17  3947 -0.022340 -0.115285 -0.136980  ... -0.045329 -0.111919  0.066313  0.002395
18  4373 -0.136550 -0.089406 -0.235399  ... -0.028972 -0.175184 -0.058283  0.147797
19  2092 -0.121763  0.011065 -0.037121  ...  0.044754 -0.003087  0.164487 -0.075231
20   525 -0.040290  0.014383 -0.098967  ... -0.025394  0.034079  0.038330 -0.001341
21  4327  0.008227  0.073899 -0.323967  ... -0.106570 -0.051692 -0.093490  0.029534
22  3048 -0.320315  0.078290 -0.083182  ...  0.028016 -0.018100 -0.128452  0.069972
23  2665 -0.076167 -0.006064 -0.001902  ...  0.086562 -0.132328  0.146198  0.029200
24  4940 -0.113099  0.047643 -0.053024  ...  0.010227 -0.008233 -0.029304  0.090511

[25 rows x 16 columns]

In [128]:
#Sorts by specific factor
movie_items_data.sort_values(by='Factor1', ascending=False)

Movie ID  ...  Factor15
86      4327  ... -2.247246
37       414  ... -1.959942
85      3049  ...  0.128814
90      8467  ...  1.616338
68       854  ... -0.931746
..       ...  ...       ...
16       122  ... -0.314937
59       680  ... -1.833900
27       238  ... -2.267831
33       278  ... -0.779991
50       603  ...  0.752413

[100 rows x 17 columns]

In [129]:
#Selects the whole row of the specified Movie ID
movie_items_data[movie_items_data['Movie ID'] == 13]

Movie ID                Title   Factor1  ...  Factor13  Factor14  Factor15
2        13  Forrest Gump (1994) -2.240888  ... -0.330276 -2.209004 -0.419092

[1 rows x 17 columns]

In [131]:
#Selects the whole row of the specified Movie ID with the minimum loading score (replace .min with .max for maximum)
movie_items_data[movie_items_data['Factor7'] == movie_items_data['Factor7'].min() ]

Movie ID  ... Factor15
79      1894  ...  0.56464

[1 rows x 17 columns]

In [133]:
#Calculates the dot product between the User,movie and the factor. Change User/Movie/factor to compare two
np.array(movie_users_data[movie_users_data['User'] == 768].loc[:,'Factor1':]).dot(np.array(movie_items_data[movie_items_data['Movie ID']==1422].loc[:,'Factor1':]).reshape(-1,1))

array([[0.0159661]])

In [31]:
#Selects the whole row of the specified User
movie_users_data[movie_users_data['User'] == 156]

User   Factor1   Factor2  Factor3  ...  Factor12  Factor13  Factor14  Factor15
1   156 -0.189652 -0.178979 -0.09149  ... -0.048606  0.045916  0.113671  0.179873

[1 rows x 16 columns]

In [61]:
np.array(movie_items_data[movie_items_data['Movie ID']==558].loc[:,'Title':])

array([['Spider-Man 2 (2004)', 2.2352233063746585, -0.7881294761636518,
        0.5967221341575716, -0.40008219852561283, -1.246622711078014,
        -1.507203113683306, -0.21991090147438985, -0.4862538356609814,
        0.3316574543781727, -1.8337552665430414, -2.243340340044728,
        -1.1979378607869537, -1.4508122479345416, -2.381119005004064,
        -0.4557528272511082]], dtype=object)

In [32]:
movie_items_data.drop(['Movie ID'],axis=1).values[0][1:]

array([-1.5218476932977845, -1.0385074424076217, 2.0272691992004397,
       0.24793252416549907, -0.5945476708705433, 2.5132599646492184,
       -1.8489100782588614, 0.47670996550851713, -0.22414630395868232,
       -0.7606806322851536, -0.973915043301705, 0.8623788058062587,
       0.4038611510962773, 1.129616009775629, -0.24880587477821164],
      dtype=object)

In [51]:
movie_users_data.shape

(25, 16)

In [49]:
def recommend_movie(user):
  user = np.array(movie_users_data[movie_users_data['User'] == user].loc[:,'Factor1':])
  scores = pd.DataFrame(columns=['ratings','Movie'])
  for i in movie_items_data.drop(['Movie ID'],axis=1).values:
    rating = user.dot(i[1:].reshape(-1,1))
    movie_dict = {'ratings':rating, 'Movie':i[0]}
    scores = scores.append(movie_dict, ignore_index=True)
  return scores.sort_values('ratings', ascending=False).head(3)

In [90]:
def recommends_movie(user, num_recommendations):
  user = np.array(movie_users_data[movie_users_data['User'] == user].loc[:,'Factor1':])
  scores = pd.DataFrame(columns=['ratings','Movie'])
  movie_id = movie_items_data['Movie ID']
  count = 0
  for i in movie_items_data.drop(['Movie ID'],axis=1).values:
    rating = user.dot(i[1:].reshape(-1,1))
    movie_dict = {'ratings':rating,'Movie':i[0],'Movie ID':movie_id[count]}
    scores = scores.append(movie_dict, ignore_index=True)
    count += 1
  return scores.sort_values('ratings', ascending=False).head(num_recommendations)

In [135]:
#Recommends movies based on User. Note: Index is incorrect and needs fixing
#recommender(3947)
recommends_movie(768, 2)

ratings                Movie  Movie ID
47  [[0.30038024641714217]]       Titanic (1997)     597.0
13  [[0.09907837413201345]]  Pretty Woman (1990)     114.0