<a href="https://colab.research.google.com/github/rpolea/CE888/blob/main/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np

In [6]:
df= pd.read_csv('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv',header=None)

In [7]:
df.head(10)
df.shape

(24983, 101)

In [8]:
df = df.replace(99, np.nan)

In [9]:
df = df.drop([0], axis = 1)

In [10]:
df.describe()

1             2    ...           99           100
count  16452.000000  18184.000000  ...  10910.000000  9943.000000
mean       0.904573      0.208460  ...     -0.031244     1.354711
std        5.171798      5.597327  ...      5.176806     5.300409
min       -9.950000     -9.950000  ...     -9.950000    -9.950000
25%       -2.670000     -4.420000  ...     -4.170000    -2.330000
50%        1.600000      0.830000  ...      0.290000     2.140000
75%        4.900000      4.820000  ...      3.980000     5.730000
max        9.370000      9.370000  ...      9.370000     9.370000

[8 rows x 100 columns]

In [11]:
df.shape

(24983, 100)

In [12]:
df.head(15)

1     2     3     4     5     6    ...   95    96    97    98    99    100
0  -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1   4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2    NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3    NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4   8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60
5  -6.17 -3.54  0.44 -8.50 -7.09 -4.32  ... -2.18 -3.35  0.05 -9.08 -5.05 -3.45
6    NaN   NaN   NaN   NaN  8.59 -9.85  ...   NaN  2.33   NaN   NaN   NaN   NaN
7   6.84  3.16  9.17 -6.21 -8.16 -1.70  ... -3.16 -3.35  2.14 -0.05  1.31  0.00
8  -3.79 -3.54 -9.42 -6.89 -8.74 -0.29  ... -0.29 -0.29 -0.29 -0.29 -3.40 -4.95
9   3.01  5.15  5.15  3.01  6.41  5.15  ...   NaN   NaN   NaN   NaN   NaN   NaN
10 -2.91  4.08   NaN   NaN -5.73   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
11  1.31  1.80  2.57 -2.38  0.73  0.73  ...  3.45  5.44  4.08  2.48  4.51  4.66
12   NaN   NaN   NaN   NaN  5.87   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
13  9.22  9.27  9.22  8.30  7.43  0.44  ...  5.53 -5.92  8.20  8.98 -8.16  6.50
14  8.79 -5.78  6.02  3.69  7.77 -5.83  ... -8.74 -3.01  8.30 -4.81 -2.38 -5.97

[15 rows x 100 columns]

In [13]:
#To find out the average rating of the lowest/highest
joke_mean_sorted = sorted(df.mean())
joke_mean_max = max(joke_mean_sorted)
joke_mean_min = min(joke_mean_sorted)

print('Max ', joke_mean_max, 'Min ', joke_mean_min)
#print('Full list sorted: ')
#joke_mean_sorted

Max  3.6650848950824937 Min  -3.8338796373689923


In [14]:
df.min().min()

-9.95

In [16]:
#Finds specific value of user and joke
df.iloc[6075,35]

2.62

In [17]:
arr = df.values
arr

array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [ 2.43,  2.67, -3.98, ...,   nan,   nan,   nan]])

In [18]:
def replace(orig, percentage):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """

  new_data = orig.copy()
  rated = np.where(np.isnan(arr))
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [19]:
user_ratings,idx = replace(arr, 0.1)

In [20]:
user_ratings

array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan,   nan,   nan, ...,   nan,   nan, 99.  ],
       [  nan, 99.  , 99.  , ...,   nan,   nan, 99.  ],
       [ 2.43,  2.67, -3.98, ...,   nan,   nan,   nan]])

In [21]:
n_latent_factors = 4

latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [23]:
latent_user_preferences

array([[0.18992783, 0.06666254, 0.68671834, 0.98633159],
       [0.8631545 , 0.2518033 , 0.14166336, 0.51266218],
       [0.34579811, 0.8376381 , 0.04407484, 0.7471199 ],
       ...,
       [0.9714835 , 0.0080286 , 0.78895015, 0.63955262],
       [0.44179039, 0.28684629, 0.10643828, 0.22700967],
       [0.50241238, 0.16777109, 0.13717978, 0.42183924]])

In [24]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    

def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                if (rating != 99 and not np.isnan(rating)):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
        mse_history.append(mse)
    return mse_history

In [25]:
sgd(150)

Iteration 0/150:	MSE=25.629424
Iteration 1/150:	MSE=24.972801
Iteration 2/150:	MSE=24.838039
Iteration 3/150:	MSE=24.713616
Iteration 4/150:	MSE=24.588210
Iteration 5/150:	MSE=24.461020


KeyboardInterrupt: ignored

In [26]:
#prediction for validation set
error_list = []
for i,j in zip(idx[0],idx[1]):
  error_list.append(predict_rating(i,j) - arr[i,j])

final_mse = (np.array(error_list)**2).mean()
print(final_mse)

nan


In [27]:
#prediction for nans
np.where(np.isnan(arr))

for i,j in zip(np.where(np.isnan(arr))[0], np.where(np.isnan(arr))[1]):
  arr[i,j] = predict_rating(i,j)

In [28]:
np.where(np.isnan(arr))

(array([], dtype=int64), array([], dtype=int64))

In [29]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[0.95424289, 0.46701967, 0.53438235, ..., 1.08508212, 0.1872029 ,
        1.54233347],
       [0.66638764, 0.29722807, 0.37087682, ..., 1.00544884, 0.29776825,
        1.19651376],
       [1.21840101, 0.55706146, 0.71184026, ..., 1.47532385, 0.46471216,
        2.02533925],
       ...,
       [0.95574251, 0.45726844, 0.46586402, ..., 1.2287122 , 0.24417972,
        1.64869119],
       [0.49537439, 0.22413467, 0.26344588, ..., 0.65683978, 0.20130018,
        0.86199748],
       [0.68250049, 0.31281946, 0.37942142, ..., 0.92301962, 0.25588438,
        1.1792985 ]])

In [30]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns

In [31]:
comparison_data
# For each data point, the number on the left is the original value from the dataset, the number on the right is the prediction

1    ...                         100
0      (-7.82, 0.9542428861823574)  ...   (nan, 1.5423334674228586)
1        (4.08, 0.666387644383855)  ...  (1.07, 1.1965137613253876)
2        (nan, 1.2184010058466037)  ...   (nan, 2.0253392496392424)
3        (nan, 0.8138557049629382)  ...   (99.0, 1.401689239616851)
4        (8.5, 1.0039040423401158)  ...   (1.6, 1.6895503401975074)
...                            ...  ...                         ...
24978   (0.44, 0.6669636519055321)  ...  (7.43, 1.2141885954490224)
24979   (9.13, 0.8206052592663043)  ...  (8.45, 1.3396525622817625)
24980    (nan, 0.9557425085130066)  ...  (99.0, 1.6486911878301422)
24981   (nan, 0.49537438643030324)  ...  (99.0, 0.8619974772610641)
24982   (2.43, 0.6825004949209692)  ...   (nan, 1.1792984977676926)

[24983 rows x 100 columns]

In [32]:
#movies dataset

#Matrix for movies and their factors
movie_items_data = pd.read_excel('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/movies_latent_factors.xlsx', sheet_name='Items')
#Matrix for users and their factors
movie_users_data = pd.read_excel('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/movies_latent_factors.xlsx', sheet_name='Users')

In [33]:
movie_users_data.head(5)

User   Factor1   Factor2   Factor3  ...  Factor12  Factor13  Factor14  Factor15
0  4768 -0.204024  0.161079 -0.090447  ...  0.355404  0.007108 -0.118663 -0.039125
1   156 -0.189652 -0.178979 -0.091490  ... -0.048606  0.045916  0.113671  0.179873
2  5323 -0.115308 -0.090886 -0.053129  ... -0.019460  0.108372  0.054471 -0.109552
3   174 -0.227462 -0.272532 -0.017231  ... -0.082396  0.036767 -0.165438  0.050692
4  4529 -0.014616 -0.102218 -0.107935  ... -0.132836 -0.039897  0.129063  0.102669

[5 rows x 16 columns]

In [34]:
#Selects the whole row of the specified Movie ID
movie_items_data[movie_items_data['Movie ID'] == 4327]

Movie ID                    Title   Factor1  ...  Factor13  Factor14  Factor15
86      4327  Charlie's Angels (2000)  4.023815  ... -1.007534  0.794589 -2.247246

[1 rows x 17 columns]

In [35]:
#Selects the whole row of the specified User
movie_users_data[movie_users_data['User'] == 4327]

User   Factor1   Factor2   Factor3  ...  Factor12  Factor13  Factor14  Factor15
21  4327  0.008227  0.073899 -0.323967  ...  -0.10657 -0.051692  -0.09349  0.029534

[1 rows x 16 columns]

In [36]:
#Selects the whole row of the specified Movie Factor with the minimum loading score (replace .min with .max for maximum)
movie_items_data[movie_items_data['Factor14'] == movie_items_data['Factor14'].min() ]

Movie ID                Title   Factor1  ...  Factor13  Factor14  Factor15
43       558  Spider-Man 2 (2004)  2.235223  ... -1.450812 -2.381119 -0.455753

[1 rows x 17 columns]

In [37]:
#Calculates the dot product between the User,movie and the factor. Change User/Movie/factor to compare two
np.array(movie_users_data[movie_users_data['User'] == 783].loc[:,'Factor1':]).dot(np.array(movie_items_data[movie_items_data['Movie ID']==597].loc[:,'Factor1':]).reshape(-1,1))

array([[0.05219643]])

In [39]:
def recommend_movie(user, num_recommendations):
  user = np.array(movie_users_data[movie_users_data['User'] == user].loc[:,'Factor1':])
  scores = pd.DataFrame(columns=['ratings','Movie'])
  movie_id = movie_items_data['Movie ID']
  count = 0
  for i in movie_items_data.drop(['Movie ID'],axis=1).values:
    rating = user.dot(i[1:].reshape(-1,1))
    movie_dict = {'ratings':rating,'Movie':i[0],'Movie ID':movie_id[count]}
    scores = scores.append(movie_dict, ignore_index=True)
    count += 1
  return scores.sort_values('ratings', ascending=False).head(num_recommendations)

In [41]:
#Recommends movies based on User and how many recommendations are required
recommend_movie(4327, 3)

ratings                 Movie  Movie ID
47   [[1.386042222743541]]        Titanic (1997)     597.0
35  [[1.0675675245300227]]  Jurassic Park (1993)     329.0
2   [[0.9572237810856431]]   Forrest Gump (1994)      13.0